# Generated by Django 3.2.8 on 2021-10-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EKYC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eKycXML', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
