# Generated by Django 3.2.8 on 2021-10-31 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekyc',
            name='user_id',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
